#!/bin/bash
BASE_URL="https://www.isc.meiji.ac.jp/~kikn/FIT/"

# PDFファイルのリスト（重複除去済み）
PDFS=(
"FIT0-guidance2013.pdf"
"Exam1-Base.pdf"
"FIT1-Base.pdf"
"Exam2-Negative.pdf"
"Exam1b-Base.pdf"
"Exam1c-Base.pdf"
"Exam1d-Base.pdf"
"FIT2-Signedb.pdf"
"Exam3-Float.pdf"
"Exam2b-Negative.pdf"
"Exam2c-Negative.pdf"
"Exam2d-Negative.pdf"
"FIT3-logic.pdf"
"Exam4-logic.pdf"
"Exam4b-logic.pdf"
"comm-2014Nov.pdf"
"Exam4c-logic.pdf"
"Exam4d-logic.pdf"
"Exam4e-logic.pdf"
"FIT4-prob.pdf"
"Exam5-Prob.pdf"
"FIT5-state.pdf"
"Exam6-FSM.pdf"
"Exam6b-FSM.pdf"
"Exam6c-FSM.pdf"
"Exam6d-FSM.pdf"
"Exam6e-FSM.pdf"
"FIT6-ECC.pdf"
"Exam7-ECC.pdf"
"Exam7b-ECC.pdf"
"Exam7c-ECC.pdf"
"Exam7d-ECC.pdf"
"Exam7e-ECC.pdf"
"FIT7-FB.pdf"
"FIT8-Stack.pdf"
"Exam8-Stack.pdf"
"Exam8b-Stack.pdf"
"Exam8c-Stack.pdf"
"Exam8d-Stack.pdf"
"FIT9-Tree.pdf"
"FIT10-Sort.pdf"
"Exam9-Sort.pdf"
"Exam9b-Sort.pdf"
"FIT11-Orderb.pdf"
"FIT12-Progb.pdf"
"FIT4-probb.pdf"
)

# ダウンロード実行
for pdf in "${PDFS[@]}"; do
  echo "Downloading: $pdf"
  curl -s -o "$pdf" "${BASE_URL}${pdf}"
done

echo "Download completed!"
